name: CI

on:
  push:
    branches: [master]

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
  DB_URL: ${{ secrets.DB_URL }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  JWT_EXPIRY: ${{ secrets.JWT_EXPIRY }}

jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm test
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  build-and-deploy:
    name: Build and Deploy
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to container registry
        run: HEROKU_API_KEY=${{ env.HEROKU_API_KEY }} heroku container:login
      - name: Build and push
        run: HEROKU_API_KEY=${{ env.HEROKU_API_KEY }} heroku container:push -a ${{ env.HEROKU_APP_NAME }} web
      - name: Set environment variables
        run: HEROKU_API_KEY=${{ env.HEROKU_API_KEY }} heroku config:set DB_URL="${{ env.DB_URL }}" JWT_SECRET="${{ env.JWT_SECRET }}" JWT_EXPIRY="${{ env.JWT_EXPIRY }}" -a ${{ env.HEROKU_APP_NAME }}
      - name: Release
        run: HEROKU_API_KEY=${{ env.HEROKU_API_KEY }} heroku container:release -a ${{ env.HEROKU_APP_NAME }} web
